// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/tvmgmtv1/tvshows.proto

package tvmgmtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTVShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Overview      string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	PosterPath    string                 `protobuf:"bytes,5,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath  string                 `protobuf:"bytes,6,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	Genres        []string               `protobuf:"bytes,7,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTVShowRequest) Reset() {
	*x = AddTVShowRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTVShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTVShowRequest) ProtoMessage() {}

func (x *AddTVShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTVShowRequest.ProtoReflect.Descriptor instead.
func (*AddTVShowRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{0}
}

func (x *AddTVShowRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *AddTVShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTVShowRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddTVShowRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *AddTVShowRequest) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *AddTVShowRequest) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *AddTVShowRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type AddTVShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTVShowResponse) Reset() {
	*x = AddTVShowResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTVShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTVShowResponse) ProtoMessage() {}

func (x *AddTVShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTVShowResponse.ProtoReflect.Descriptor instead.
func (*AddTVShowResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{1}
}

func (x *AddTVShowResponse) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

type RemoveTVShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTVShowRequest) Reset() {
	*x = RemoveTVShowRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTVShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTVShowRequest) ProtoMessage() {}

func (x *RemoveTVShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTVShowRequest.ProtoReflect.Descriptor instead.
func (*RemoveTVShowRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveTVShowRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

type RemoveTVShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTVShowResponse) Reset() {
	*x = RemoveTVShowResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTVShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTVShowResponse) ProtoMessage() {}

func (x *RemoveTVShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTVShowResponse.ProtoReflect.Descriptor instead.
func (*RemoveTVShowResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{3}
}

type RefreshMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshMetadataRequest) Reset() {
	*x = RefreshMetadataRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMetadataRequest) ProtoMessage() {}

func (x *RefreshMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshMetadataRequest.ProtoReflect.Descriptor instead.
func (*RefreshMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshMetadataRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

type RefreshMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshMetadataResponse) Reset() {
	*x = RefreshMetadataResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMetadataResponse) ProtoMessage() {}

func (x *RefreshMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshMetadataResponse.ProtoReflect.Descriptor instead.
func (*RefreshMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{5}
}

type ListTVShowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTVShowsRequest) Reset() {
	*x = ListTVShowsRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTVShowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTVShowsRequest) ProtoMessage() {}

func (x *ListTVShowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTVShowsRequest.ProtoReflect.Descriptor instead.
func (*ListTVShowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{6}
}

func (x *ListTVShowsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTVShowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTVShowsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListTVShowsRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ListTVShowsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListTVShowsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListTVShowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*TVSeries            `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTVShowsResponse) Reset() {
	*x = ListTVShowsResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTVShowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTVShowsResponse) ProtoMessage() {}

func (x *ListTVShowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTVShowsResponse.ProtoReflect.Descriptor instead.
func (*ListTVShowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{7}
}

func (x *ListTVShowsResponse) GetSeries() []*TVSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *ListTVShowsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTVShowsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTVShowsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTVShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTVShowRequest) Reset() {
	*x = GetTVShowRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTVShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTVShowRequest) ProtoMessage() {}

func (x *GetTVShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTVShowRequest.ProtoReflect.Descriptor instead.
func (*GetTVShowRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{8}
}

func (x *GetTVShowRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

type GetTVShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        *TVSeries              `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTVShowResponse) Reset() {
	*x = GetTVShowResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTVShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTVShowResponse) ProtoMessage() {}

func (x *GetTVShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTVShowResponse.ProtoReflect.Descriptor instead.
func (*GetTVShowResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{9}
}

func (x *GetTVShowResponse) GetSeries() *TVSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

type UpdateEpisodeMonitoredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	Monitored     bool                   `protobuf:"varint,2,opt,name=monitored,proto3" json:"monitored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEpisodeMonitoredRequest) Reset() {
	*x = UpdateEpisodeMonitoredRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEpisodeMonitoredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEpisodeMonitoredRequest) ProtoMessage() {}

func (x *UpdateEpisodeMonitoredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEpisodeMonitoredRequest.ProtoReflect.Descriptor instead.
func (*UpdateEpisodeMonitoredRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateEpisodeMonitoredRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *UpdateEpisodeMonitoredRequest) GetMonitored() bool {
	if x != nil {
		return x.Monitored
	}
	return false
}

type UpdateEpisodeMonitoredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEpisodeMonitoredResponse) Reset() {
	*x = UpdateEpisodeMonitoredResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEpisodeMonitoredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEpisodeMonitoredResponse) ProtoMessage() {}

func (x *UpdateEpisodeMonitoredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEpisodeMonitoredResponse.ProtoReflect.Descriptor instead.
func (*UpdateEpisodeMonitoredResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{11}
}

type UpdateSeasonMonitoredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeasonId      string                 `protobuf:"bytes,1,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	Monitored     bool                   `protobuf:"varint,2,opt,name=monitored,proto3" json:"monitored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeasonMonitoredRequest) Reset() {
	*x = UpdateSeasonMonitoredRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeasonMonitoredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeasonMonitoredRequest) ProtoMessage() {}

func (x *UpdateSeasonMonitoredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeasonMonitoredRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeasonMonitoredRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSeasonMonitoredRequest) GetSeasonId() string {
	if x != nil {
		return x.SeasonId
	}
	return ""
}

func (x *UpdateSeasonMonitoredRequest) GetMonitored() bool {
	if x != nil {
		return x.Monitored
	}
	return false
}

type UpdateSeasonMonitoredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeasonMonitoredResponse) Reset() {
	*x = UpdateSeasonMonitoredResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeasonMonitoredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeasonMonitoredResponse) ProtoMessage() {}

func (x *UpdateSeasonMonitoredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeasonMonitoredResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeasonMonitoredResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{13}
}

type TVSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TmdbId        int32                  `protobuf:"varint,2,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OriginalName  string                 `protobuf:"bytes,4,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Overview      string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	Tagline       string                 `protobuf:"bytes,7,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Network       string                 `protobuf:"bytes,9,opt,name=network,proto3" json:"network,omitempty"`
	FirstAirDate  string                 `protobuf:"bytes,10,opt,name=first_air_date,json=firstAirDate,proto3" json:"first_air_date,omitempty"`
	LastAirDate   string                 `protobuf:"bytes,11,opt,name=last_air_date,json=lastAirDate,proto3" json:"last_air_date,omitempty"`
	VoteAverage   float64                `protobuf:"fixed64,12,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
	Genres        []string               `protobuf:"bytes,13,rep,name=genres,proto3" json:"genres,omitempty"`
	PosterPath    string                 `protobuf:"bytes,14,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath  string                 `protobuf:"bytes,15,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,16,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	BackdropUrl   string                 `protobuf:"bytes,17,opt,name=backdrop_url,json=backdropUrl,proto3" json:"backdrop_url,omitempty"`
	Monitored     bool                   `protobuf:"varint,18,opt,name=monitored,proto3" json:"monitored,omitempty"`
	Seasons       []*TVSeason            `protobuf:"bytes,19,rep,name=seasons,proto3" json:"seasons,omitempty"`
	TotalEpisodes int32                  `protobuf:"varint,20,opt,name=total_episodes,json=totalEpisodes,proto3" json:"total_episodes,omitempty"`
	TotalSeasons  int32                  `protobuf:"varint,21,opt,name=total_seasons,json=totalSeasons,proto3" json:"total_seasons,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TVSeries) Reset() {
	*x = TVSeries{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TVSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TVSeries) ProtoMessage() {}

func (x *TVSeries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TVSeries.ProtoReflect.Descriptor instead.
func (*TVSeries) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{14}
}

func (x *TVSeries) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TVSeries) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *TVSeries) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TVSeries) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *TVSeries) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *TVSeries) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *TVSeries) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *TVSeries) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TVSeries) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TVSeries) GetFirstAirDate() string {
	if x != nil {
		return x.FirstAirDate
	}
	return ""
}

func (x *TVSeries) GetLastAirDate() string {
	if x != nil {
		return x.LastAirDate
	}
	return ""
}

func (x *TVSeries) GetVoteAverage() float64 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

func (x *TVSeries) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *TVSeries) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *TVSeries) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *TVSeries) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *TVSeries) GetBackdropUrl() string {
	if x != nil {
		return x.BackdropUrl
	}
	return ""
}

func (x *TVSeries) GetMonitored() bool {
	if x != nil {
		return x.Monitored
	}
	return false
}

func (x *TVSeries) GetSeasons() []*TVSeason {
	if x != nil {
		return x.Seasons
	}
	return nil
}

func (x *TVSeries) GetTotalEpisodes() int32 {
	if x != nil {
		return x.TotalEpisodes
	}
	return 0
}

func (x *TVSeries) GetTotalSeasons() int32 {
	if x != nil {
		return x.TotalSeasons
	}
	return 0
}

func (x *TVSeries) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TVSeries) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TVSeason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SeriesId      string                 `protobuf:"bytes,2,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	SeasonNumber  int32                  `protobuf:"varint,3,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Overview      string                 `protobuf:"bytes,5,opt,name=overview,proto3" json:"overview,omitempty"`
	EpisodeCount  int32                  `protobuf:"varint,6,opt,name=episode_count,json=episodeCount,proto3" json:"episode_count,omitempty"`
	AirDate       string                 `protobuf:"bytes,7,opt,name=air_date,json=airDate,proto3" json:"air_date,omitempty"`
	PosterPath    string                 `protobuf:"bytes,8,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	Monitored     bool                   `protobuf:"varint,9,opt,name=monitored,proto3" json:"monitored,omitempty"`
	Episodes      []*TVEpisode           `protobuf:"bytes,10,rep,name=episodes,proto3" json:"episodes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TVSeason) Reset() {
	*x = TVSeason{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TVSeason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TVSeason) ProtoMessage() {}

func (x *TVSeason) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TVSeason.ProtoReflect.Descriptor instead.
func (*TVSeason) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{15}
}

func (x *TVSeason) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TVSeason) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *TVSeason) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *TVSeason) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TVSeason) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *TVSeason) GetEpisodeCount() int32 {
	if x != nil {
		return x.EpisodeCount
	}
	return 0
}

func (x *TVSeason) GetAirDate() string {
	if x != nil {
		return x.AirDate
	}
	return ""
}

func (x *TVSeason) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *TVSeason) GetMonitored() bool {
	if x != nil {
		return x.Monitored
	}
	return false
}

func (x *TVSeason) GetEpisodes() []*TVEpisode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *TVSeason) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TVSeason) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TVEpisode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SeriesId       string                 `protobuf:"bytes,2,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	SeasonId       string                 `protobuf:"bytes,3,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	TmdbId         int32                  `protobuf:"varint,4,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	EpisodeNumber  int32                  `protobuf:"varint,5,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	SeasonNumber   int32                  `protobuf:"varint,6,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	AbsoluteNumber int32                  `protobuf:"varint,7,opt,name=absolute_number,json=absoluteNumber,proto3" json:"absolute_number,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Overview       string                 `protobuf:"bytes,9,opt,name=overview,proto3" json:"overview,omitempty"`
	AirDate        string                 `protobuf:"bytes,10,opt,name=air_date,json=airDate,proto3" json:"air_date,omitempty"`
	StillPath      string                 `protobuf:"bytes,11,opt,name=still_path,json=stillPath,proto3" json:"still_path,omitempty"`
	Monitored      bool                   `protobuf:"varint,12,opt,name=monitored,proto3" json:"monitored,omitempty"`
	HasFile        bool                   `protobuf:"varint,13,opt,name=has_file,json=hasFile,proto3" json:"has_file,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TVEpisode) Reset() {
	*x = TVEpisode{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TVEpisode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TVEpisode) ProtoMessage() {}

func (x *TVEpisode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TVEpisode.ProtoReflect.Descriptor instead.
func (*TVEpisode) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{16}
}

func (x *TVEpisode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TVEpisode) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *TVEpisode) GetSeasonId() string {
	if x != nil {
		return x.SeasonId
	}
	return ""
}

func (x *TVEpisode) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *TVEpisode) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *TVEpisode) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *TVEpisode) GetAbsoluteNumber() int32 {
	if x != nil {
		return x.AbsoluteNumber
	}
	return 0
}

func (x *TVEpisode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TVEpisode) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *TVEpisode) GetAirDate() string {
	if x != nil {
		return x.AirDate
	}
	return ""
}

func (x *TVEpisode) GetStillPath() string {
	if x != nil {
		return x.StillPath
	}
	return ""
}

func (x *TVEpisode) GetMonitored() bool {
	if x != nil {
		return x.Monitored
	}
	return false
}

func (x *TVEpisode) GetHasFile() bool {
	if x != nil {
		return x.HasFile
	}
	return false
}

func (x *TVEpisode) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TVEpisode) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddEpisodeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Quality       string                 `protobuf:"bytes,3,opt,name=quality,proto3" json:"quality,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Container     string                 `protobuf:"bytes,5,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEpisodeFileRequest) Reset() {
	*x = AddEpisodeFileRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEpisodeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEpisodeFileRequest) ProtoMessage() {}

func (x *AddEpisodeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEpisodeFileRequest.ProtoReflect.Descriptor instead.
func (*AddEpisodeFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{17}
}

func (x *AddEpisodeFileRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *AddEpisodeFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AddEpisodeFileRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *AddEpisodeFileRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AddEpisodeFileRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type AddEpisodeFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEpisodeFileResponse) Reset() {
	*x = AddEpisodeFileResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEpisodeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEpisodeFileResponse) ProtoMessage() {}

func (x *AddEpisodeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEpisodeFileResponse.ProtoReflect.Descriptor instead.
func (*AddEpisodeFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{18}
}

func (x *AddEpisodeFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type RemoveEpisodeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEpisodeFileRequest) Reset() {
	*x = RemoveEpisodeFileRequest{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEpisodeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEpisodeFileRequest) ProtoMessage() {}

func (x *RemoveEpisodeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEpisodeFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveEpisodeFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveEpisodeFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type RemoveEpisodeFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEpisodeFileResponse) Reset() {
	*x = RemoveEpisodeFileResponse{}
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEpisodeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEpisodeFileResponse) ProtoMessage() {}

func (x *RemoveEpisodeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tvmgmtv1_tvshows_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEpisodeFileResponse.ProtoReflect.Descriptor instead.
func (*RemoveEpisodeFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP(), []int{20}
}

var File_proto_tvmgmtv1_tvshows_proto protoreflect.FileDescriptor

const file_proto_tvmgmtv1_tvshows_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/tvmgmtv1/tvshows.proto\x12\x13muxcore.media.tv.v1\"\xcd\x01\n" +
	"\x10AddTVShowRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x1f\n" +
	"\vposter_path\x18\x05 \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\x06 \x01(\tR\fbackdropPath\x12\x16\n" +
	"\x06genres\x18\a \x03(\tR\x06genres\"0\n" +
	"\x11AddTVShowResponse\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId\"2\n" +
	"\x13RemoveTVShowRequest\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId\"\x16\n" +
	"\x14RemoveTVShowResponse\"5\n" +
	"\x16RefreshMetadataRequest\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId\"\x19\n" +
	"\x17RefreshMetadataResponse\"\xab\x01\n" +
	"\x12ListTVShowsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\tR\tsortOrder\"\x93\x01\n" +
	"\x13ListTVShowsResponse\x125\n" +
	"\x06series\x18\x01 \x03(\v2\x1d.muxcore.media.tv.v1.TVSeriesR\x06series\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"/\n" +
	"\x10GetTVShowRequest\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId\"J\n" +
	"\x11GetTVShowResponse\x125\n" +
	"\x06series\x18\x01 \x01(\v2\x1d.muxcore.media.tv.v1.TVSeriesR\x06series\"\\\n" +
	"\x1dUpdateEpisodeMonitoredRequest\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1c\n" +
	"\tmonitored\x18\x02 \x01(\bR\tmonitored\" \n" +
	"\x1eUpdateEpisodeMonitoredResponse\"Y\n" +
	"\x1cUpdateSeasonMonitoredRequest\x12\x1b\n" +
	"\tseason_id\x18\x01 \x01(\tR\bseasonId\x12\x1c\n" +
	"\tmonitored\x18\x02 \x01(\bR\tmonitored\"\x1f\n" +
	"\x1dUpdateSeasonMonitoredResponse\"\xd6\x05\n" +
	"\bTVSeries\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atmdb_id\x18\x02 \x01(\x05R\x06tmdbId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\roriginal_name\x18\x04 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\x12\x18\n" +
	"\atagline\x18\a \x01(\tR\atagline\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\anetwork\x18\t \x01(\tR\anetwork\x12$\n" +
	"\x0efirst_air_date\x18\n" +
	" \x01(\tR\ffirstAirDate\x12\"\n" +
	"\rlast_air_date\x18\v \x01(\tR\vlastAirDate\x12!\n" +
	"\fvote_average\x18\f \x01(\x01R\vvoteAverage\x12\x16\n" +
	"\x06genres\x18\r \x03(\tR\x06genres\x12\x1f\n" +
	"\vposter_path\x18\x0e \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\x0f \x01(\tR\fbackdropPath\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x10 \x01(\tR\tposterUrl\x12!\n" +
	"\fbackdrop_url\x18\x11 \x01(\tR\vbackdropUrl\x12\x1c\n" +
	"\tmonitored\x18\x12 \x01(\bR\tmonitored\x127\n" +
	"\aseasons\x18\x13 \x03(\v2\x1d.muxcore.media.tv.v1.TVSeasonR\aseasons\x12%\n" +
	"\x0etotal_episodes\x18\x14 \x01(\x05R\rtotalEpisodes\x12#\n" +
	"\rtotal_seasons\x18\x15 \x01(\x05R\ftotalSeasons\x12\x1d\n" +
	"\n" +
	"created_at\x18\x16 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\tR\tupdatedAt\"\x85\x03\n" +
	"\bTVSeason\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tseries_id\x18\x02 \x01(\tR\bseriesId\x12#\n" +
	"\rseason_number\x18\x03 \x01(\x05R\fseasonNumber\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\boverview\x18\x05 \x01(\tR\boverview\x12#\n" +
	"\repisode_count\x18\x06 \x01(\x05R\fepisodeCount\x12\x19\n" +
	"\bair_date\x18\a \x01(\tR\aairDate\x12\x1f\n" +
	"\vposter_path\x18\b \x01(\tR\n" +
	"posterPath\x12\x1c\n" +
	"\tmonitored\x18\t \x01(\bR\tmonitored\x12:\n" +
	"\bepisodes\x18\n" +
	" \x03(\v2\x1e.muxcore.media.tv.v1.TVEpisodeR\bepisodes\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xc4\x03\n" +
	"\tTVEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tseries_id\x18\x02 \x01(\tR\bseriesId\x12\x1b\n" +
	"\tseason_id\x18\x03 \x01(\tR\bseasonId\x12\x17\n" +
	"\atmdb_id\x18\x04 \x01(\x05R\x06tmdbId\x12%\n" +
	"\x0eepisode_number\x18\x05 \x01(\x05R\repisodeNumber\x12#\n" +
	"\rseason_number\x18\x06 \x01(\x05R\fseasonNumber\x12'\n" +
	"\x0fabsolute_number\x18\a \x01(\x05R\x0eabsoluteNumber\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x1a\n" +
	"\boverview\x18\t \x01(\tR\boverview\x12\x19\n" +
	"\bair_date\x18\n" +
	" \x01(\tR\aairDate\x12\x1d\n" +
	"\n" +
	"still_path\x18\v \x01(\tR\tstillPath\x12\x1c\n" +
	"\tmonitored\x18\f \x01(\bR\tmonitored\x12\x19\n" +
	"\bhas_file\x18\r \x01(\bR\ahasFile\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\xaa\x01\n" +
	"\x15AddEpisodeFileRequest\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x18\n" +
	"\aquality\x18\x03 \x01(\tR\aquality\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1c\n" +
	"\tcontainer\x18\x05 \x01(\tR\tcontainer\"1\n" +
	"\x16AddEpisodeFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"3\n" +
	"\x18RemoveEpisodeFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x1b\n" +
	"\x19RemoveEpisodeFileResponse2\xe5\a\n" +
	"\x13TvManagementService\x12Z\n" +
	"\tAddTVShow\x12%.muxcore.media.tv.v1.AddTVShowRequest\x1a&.muxcore.media.tv.v1.AddTVShowResponse\x12c\n" +
	"\fRemoveTVShow\x12(.muxcore.media.tv.v1.RemoveTVShowRequest\x1a).muxcore.media.tv.v1.RemoveTVShowResponse\x12l\n" +
	"\x0fRefreshMetadata\x12+.muxcore.media.tv.v1.RefreshMetadataRequest\x1a,.muxcore.media.tv.v1.RefreshMetadataResponse\x12`\n" +
	"\vListTVShows\x12'.muxcore.media.tv.v1.ListTVShowsRequest\x1a(.muxcore.media.tv.v1.ListTVShowsResponse\x12Z\n" +
	"\tGetTVShow\x12%.muxcore.media.tv.v1.GetTVShowRequest\x1a&.muxcore.media.tv.v1.GetTVShowResponse\x12\x81\x01\n" +
	"\x16UpdateEpisodeMonitored\x122.muxcore.media.tv.v1.UpdateEpisodeMonitoredRequest\x1a3.muxcore.media.tv.v1.UpdateEpisodeMonitoredResponse\x12~\n" +
	"\x15UpdateSeasonMonitored\x121.muxcore.media.tv.v1.UpdateSeasonMonitoredRequest\x1a2.muxcore.media.tv.v1.UpdateSeasonMonitoredResponse\x12i\n" +
	"\x0eAddEpisodeFile\x12*.muxcore.media.tv.v1.AddEpisodeFileRequest\x1a+.muxcore.media.tv.v1.AddEpisodeFileResponse\x12r\n" +
	"\x11RemoveEpisodeFile\x12-.muxcore.media.tv.v1.RemoveEpisodeFileRequest\x1a..muxcore.media.tv.v1.RemoveEpisodeFileResponseB@Z>github.com/Muxcore-Media/media-tvshows/proto/tvmgmtv1;tvmgmtv1b\x06proto3"

var (
	file_proto_tvmgmtv1_tvshows_proto_rawDescOnce sync.Once
	file_proto_tvmgmtv1_tvshows_proto_rawDescData []byte
)

func file_proto_tvmgmtv1_tvshows_proto_rawDescGZIP() []byte {
	file_proto_tvmgmtv1_tvshows_proto_rawDescOnce.Do(func() {
		file_proto_tvmgmtv1_tvshows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tvmgmtv1_tvshows_proto_rawDesc), len(file_proto_tvmgmtv1_tvshows_proto_rawDesc)))
	})
	return file_proto_tvmgmtv1_tvshows_proto_rawDescData
}

var file_proto_tvmgmtv1_tvshows_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_tvmgmtv1_tvshows_proto_goTypes = []any{
	(*AddTVShowRequest)(nil),               // 0: muxcore.media.tv.v1.AddTVShowRequest
	(*AddTVShowResponse)(nil),              // 1: muxcore.media.tv.v1.AddTVShowResponse
	(*RemoveTVShowRequest)(nil),            // 2: muxcore.media.tv.v1.RemoveTVShowRequest
	(*RemoveTVShowResponse)(nil),           // 3: muxcore.media.tv.v1.RemoveTVShowResponse
	(*RefreshMetadataRequest)(nil),         // 4: muxcore.media.tv.v1.RefreshMetadataRequest
	(*RefreshMetadataResponse)(nil),        // 5: muxcore.media.tv.v1.RefreshMetadataResponse
	(*ListTVShowsRequest)(nil),             // 6: muxcore.media.tv.v1.ListTVShowsRequest
	(*ListTVShowsResponse)(nil),            // 7: muxcore.media.tv.v1.ListTVShowsResponse
	(*GetTVShowRequest)(nil),               // 8: muxcore.media.tv.v1.GetTVShowRequest
	(*GetTVShowResponse)(nil),              // 9: muxcore.media.tv.v1.GetTVShowResponse
	(*UpdateEpisodeMonitoredRequest)(nil),  // 10: muxcore.media.tv.v1.UpdateEpisodeMonitoredRequest
	(*UpdateEpisodeMonitoredResponse)(nil), // 11: muxcore.media.tv.v1.UpdateEpisodeMonitoredResponse
	(*UpdateSeasonMonitoredRequest)(nil),   // 12: muxcore.media.tv.v1.UpdateSeasonMonitoredRequest
	(*UpdateSeasonMonitoredResponse)(nil),  // 13: muxcore.media.tv.v1.UpdateSeasonMonitoredResponse
	(*TVSeries)(nil),                       // 14: muxcore.media.tv.v1.TVSeries
	(*TVSeason)(nil),                       // 15: muxcore.media.tv.v1.TVSeason
	(*TVEpisode)(nil),                      // 16: muxcore.media.tv.v1.TVEpisode
	(*AddEpisodeFileRequest)(nil),          // 17: muxcore.media.tv.v1.AddEpisodeFileRequest
	(*AddEpisodeFileResponse)(nil),         // 18: muxcore.media.tv.v1.AddEpisodeFileResponse
	(*RemoveEpisodeFileRequest)(nil),       // 19: muxcore.media.tv.v1.RemoveEpisodeFileRequest
	(*RemoveEpisodeFileResponse)(nil),      // 20: muxcore.media.tv.v1.RemoveEpisodeFileResponse
}
var file_proto_tvmgmtv1_tvshows_proto_depIdxs = []int32{
	14, // 0: muxcore.media.tv.v1.ListTVShowsResponse.series:type_name -> muxcore.media.tv.v1.TVSeries
	14, // 1: muxcore.media.tv.v1.GetTVShowResponse.series:type_name -> muxcore.media.tv.v1.TVSeries
	15, // 2: muxcore.media.tv.v1.TVSeries.seasons:type_name -> muxcore.media.tv.v1.TVSeason
	16, // 3: muxcore.media.tv.v1.TVSeason.episodes:type_name -> muxcore.media.tv.v1.TVEpisode
	0,  // 4: muxcore.media.tv.v1.TvManagementService.AddTVShow:input_type -> muxcore.media.tv.v1.AddTVShowRequest
	2,  // 5: muxcore.media.tv.v1.TvManagementService.RemoveTVShow:input_type -> muxcore.media.tv.v1.RemoveTVShowRequest
	4,  // 6: muxcore.media.tv.v1.TvManagementService.RefreshMetadata:input_type -> muxcore.media.tv.v1.RefreshMetadataRequest
	6,  // 7: muxcore.media.tv.v1.TvManagementService.ListTVShows:input_type -> muxcore.media.tv.v1.ListTVShowsRequest
	8,  // 8: muxcore.media.tv.v1.TvManagementService.GetTVShow:input_type -> muxcore.media.tv.v1.GetTVShowRequest
	10, // 9: muxcore.media.tv.v1.TvManagementService.UpdateEpisodeMonitored:input_type -> muxcore.media.tv.v1.UpdateEpisodeMonitoredRequest
	12, // 10: muxcore.media.tv.v1.TvManagementService.UpdateSeasonMonitored:input_type -> muxcore.media.tv.v1.UpdateSeasonMonitoredRequest
	17, // 11: muxcore.media.tv.v1.TvManagementService.AddEpisodeFile:input_type -> muxcore.media.tv.v1.AddEpisodeFileRequest
	19, // 12: muxcore.media.tv.v1.TvManagementService.RemoveEpisodeFile:input_type -> muxcore.media.tv.v1.RemoveEpisodeFileRequest
	1,  // 13: muxcore.media.tv.v1.TvManagementService.AddTVShow:output_type -> muxcore.media.tv.v1.AddTVShowResponse
	3,  // 14: muxcore.media.tv.v1.TvManagementService.RemoveTVShow:output_type -> muxcore.media.tv.v1.RemoveTVShowResponse
	5,  // 15: muxcore.media.tv.v1.TvManagementService.RefreshMetadata:output_type -> muxcore.media.tv.v1.RefreshMetadataResponse
	7,  // 16: muxcore.media.tv.v1.TvManagementService.ListTVShows:output_type -> muxcore.media.tv.v1.ListTVShowsResponse
	9,  // 17: muxcore.media.tv.v1.TvManagementService.GetTVShow:output_type -> muxcore.media.tv.v1.GetTVShowResponse
	11, // 18: muxcore.media.tv.v1.TvManagementService.UpdateEpisodeMonitored:output_type -> muxcore.media.tv.v1.UpdateEpisodeMonitoredResponse
	13, // 19: muxcore.media.tv.v1.TvManagementService.UpdateSeasonMonitored:output_type -> muxcore.media.tv.v1.UpdateSeasonMonitoredResponse
	18, // 20: muxcore.media.tv.v1.TvManagementService.AddEpisodeFile:output_type -> muxcore.media.tv.v1.AddEpisodeFileResponse
	20, // 21: muxcore.media.tv.v1.TvManagementService.RemoveEpisodeFile:output_type -> muxcore.media.tv.v1.RemoveEpisodeFileResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_tvmgmtv1_tvshows_proto_init() }
func file_proto_tvmgmtv1_tvshows_proto_init() {
	if File_proto_tvmgmtv1_tvshows_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tvmgmtv1_tvshows_proto_rawDesc), len(file_proto_tvmgmtv1_tvshows_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tvmgmtv1_tvshows_proto_goTypes,
		DependencyIndexes: file_proto_tvmgmtv1_tvshows_proto_depIdxs,
		MessageInfos:      file_proto_tvmgmtv1_tvshows_proto_msgTypes,
	}.Build()
	File_proto_tvmgmtv1_tvshows_proto = out.File
	file_proto_tvmgmtv1_tvshows_proto_goTypes = nil
	file_proto_tvmgmtv1_tvshows_proto_depIdxs = nil
}
