// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/tvmgmtv1/tvshows.proto

package tvmgmtv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TvManagementService_AddTVShow_FullMethodName              = "/muxcore.media.tv.v1.TvManagementService/AddTVShow"
	TvManagementService_RemoveTVShow_FullMethodName           = "/muxcore.media.tv.v1.TvManagementService/RemoveTVShow"
	TvManagementService_RefreshMetadata_FullMethodName        = "/muxcore.media.tv.v1.TvManagementService/RefreshMetadata"
	TvManagementService_ListTVShows_FullMethodName            = "/muxcore.media.tv.v1.TvManagementService/ListTVShows"
	TvManagementService_ListMissing_FullMethodName            = "/muxcore.media.tv.v1.TvManagementService/ListMissing"
	TvManagementService_GetTVShow_FullMethodName              = "/muxcore.media.tv.v1.TvManagementService/GetTVShow"
	TvManagementService_UpdateTVShow_FullMethodName           = "/muxcore.media.tv.v1.TvManagementService/UpdateTVShow"
	TvManagementService_UpdateEpisodeMonitored_FullMethodName = "/muxcore.media.tv.v1.TvManagementService/UpdateEpisodeMonitored"
	TvManagementService_UpdateSeasonMonitored_FullMethodName  = "/muxcore.media.tv.v1.TvManagementService/UpdateSeasonMonitored"
	TvManagementService_AddEpisodeFile_FullMethodName         = "/muxcore.media.tv.v1.TvManagementService/AddEpisodeFile"
	TvManagementService_RemoveEpisodeFile_FullMethodName      = "/muxcore.media.tv.v1.TvManagementService/RemoveEpisodeFile"
	TvManagementService_CreateTag_FullMethodName              = "/muxcore.media.tv.v1.TvManagementService/CreateTag"
	TvManagementService_DeleteTag_FullMethodName              = "/muxcore.media.tv.v1.TvManagementService/DeleteTag"
	TvManagementService_ListTags_FullMethodName               = "/muxcore.media.tv.v1.TvManagementService/ListTags"
	TvManagementService_SetItemTags_FullMethodName            = "/muxcore.media.tv.v1.TvManagementService/SetItemTags"
	TvManagementService_GetItemTags_FullMethodName            = "/muxcore.media.tv.v1.TvManagementService/GetItemTags"
	TvManagementService_GetCalendar_FullMethodName            = "/muxcore.media.tv.v1.TvManagementService/GetCalendar"
	TvManagementService_ListAlternateTitles_FullMethodName    = "/muxcore.media.tv.v1.TvManagementService/ListAlternateTitles"
	TvManagementService_AddAlternateTitle_FullMethodName      = "/muxcore.media.tv.v1.TvManagementService/AddAlternateTitle"
	TvManagementService_RemoveAlternateTitle_FullMethodName   = "/muxcore.media.tv.v1.TvManagementService/RemoveAlternateTitle"
	TvManagementService_LookupEpisode_FullMethodName          = "/muxcore.media.tv.v1.TvManagementService/LookupEpisode"
)

// TvManagementServiceClient is the client API for TvManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TvManagementServiceClient interface {
	AddTVShow(ctx context.Context, in *AddTVShowRequest, opts ...grpc.CallOption) (*AddTVShowResponse, error)
	RemoveTVShow(ctx context.Context, in *RemoveTVShowRequest, opts ...grpc.CallOption) (*RemoveTVShowResponse, error)
	RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*RefreshMetadataResponse, error)
	ListTVShows(ctx context.Context, in *ListTVShowsRequest, opts ...grpc.CallOption) (*ListTVShowsResponse, error)
	ListMissing(ctx context.Context, in *ListMissingRequest, opts ...grpc.CallOption) (*ListMissingResponse, error)
	GetTVShow(ctx context.Context, in *GetTVShowRequest, opts ...grpc.CallOption) (*GetTVShowResponse, error)
	UpdateTVShow(ctx context.Context, in *UpdateTVShowRequest, opts ...grpc.CallOption) (*UpdateTVShowResponse, error)
	UpdateEpisodeMonitored(ctx context.Context, in *UpdateEpisodeMonitoredRequest, opts ...grpc.CallOption) (*UpdateEpisodeMonitoredResponse, error)
	UpdateSeasonMonitored(ctx context.Context, in *UpdateSeasonMonitoredRequest, opts ...grpc.CallOption) (*UpdateSeasonMonitoredResponse, error)
	AddEpisodeFile(ctx context.Context, in *AddEpisodeFileRequest, opts ...grpc.CallOption) (*AddEpisodeFileResponse, error)
	RemoveEpisodeFile(ctx context.Context, in *RemoveEpisodeFileRequest, opts ...grpc.CallOption) (*RemoveEpisodeFileResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	SetItemTags(ctx context.Context, in *SetItemTagsRequest, opts ...grpc.CallOption) (*SetItemTagsResponse, error)
	GetItemTags(ctx context.Context, in *GetItemTagsRequest, opts ...grpc.CallOption) (*GetItemTagsResponse, error)
	GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*GetCalendarResponse, error)
	ListAlternateTitles(ctx context.Context, in *ListAlternateTitlesRequest, opts ...grpc.CallOption) (*ListAlternateTitlesResponse, error)
	AddAlternateTitle(ctx context.Context, in *AddAlternateTitleRequest, opts ...grpc.CallOption) (*AddAlternateTitleResponse, error)
	RemoveAlternateTitle(ctx context.Context, in *RemoveAlternateTitleRequest, opts ...grpc.CallOption) (*RemoveAlternateTitleResponse, error)
	LookupEpisode(ctx context.Context, in *LookupEpisodeRequest, opts ...grpc.CallOption) (*LookupEpisodeResponse, error)
}

type tvManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTvManagementServiceClient(cc grpc.ClientConnInterface) TvManagementServiceClient {
	return &tvManagementServiceClient{cc}
}

func (c *tvManagementServiceClient) AddTVShow(ctx context.Context, in *AddTVShowRequest, opts ...grpc.CallOption) (*AddTVShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTVShowResponse)
	err := c.cc.Invoke(ctx, TvManagementService_AddTVShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) RemoveTVShow(ctx context.Context, in *RemoveTVShowRequest, opts ...grpc.CallOption) (*RemoveTVShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTVShowResponse)
	err := c.cc.Invoke(ctx, TvManagementService_RemoveTVShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*RefreshMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshMetadataResponse)
	err := c.cc.Invoke(ctx, TvManagementService_RefreshMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) ListTVShows(ctx context.Context, in *ListTVShowsRequest, opts ...grpc.CallOption) (*ListTVShowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTVShowsResponse)
	err := c.cc.Invoke(ctx, TvManagementService_ListTVShows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) ListMissing(ctx context.Context, in *ListMissingRequest, opts ...grpc.CallOption) (*ListMissingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMissingResponse)
	err := c.cc.Invoke(ctx, TvManagementService_ListMissing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) GetTVShow(ctx context.Context, in *GetTVShowRequest, opts ...grpc.CallOption) (*GetTVShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTVShowResponse)
	err := c.cc.Invoke(ctx, TvManagementService_GetTVShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) UpdateTVShow(ctx context.Context, in *UpdateTVShowRequest, opts ...grpc.CallOption) (*UpdateTVShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTVShowResponse)
	err := c.cc.Invoke(ctx, TvManagementService_UpdateTVShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) UpdateEpisodeMonitored(ctx context.Context, in *UpdateEpisodeMonitoredRequest, opts ...grpc.CallOption) (*UpdateEpisodeMonitoredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEpisodeMonitoredResponse)
	err := c.cc.Invoke(ctx, TvManagementService_UpdateEpisodeMonitored_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) UpdateSeasonMonitored(ctx context.Context, in *UpdateSeasonMonitoredRequest, opts ...grpc.CallOption) (*UpdateSeasonMonitoredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSeasonMonitoredResponse)
	err := c.cc.Invoke(ctx, TvManagementService_UpdateSeasonMonitored_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) AddEpisodeFile(ctx context.Context, in *AddEpisodeFileRequest, opts ...grpc.CallOption) (*AddEpisodeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEpisodeFileResponse)
	err := c.cc.Invoke(ctx, TvManagementService_AddEpisodeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) RemoveEpisodeFile(ctx context.Context, in *RemoveEpisodeFileRequest, opts ...grpc.CallOption) (*RemoveEpisodeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveEpisodeFileResponse)
	err := c.cc.Invoke(ctx, TvManagementService_RemoveEpisodeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, TvManagementService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, TvManagementService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, TvManagementService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) SetItemTags(ctx context.Context, in *SetItemTagsRequest, opts ...grpc.CallOption) (*SetItemTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetItemTagsResponse)
	err := c.cc.Invoke(ctx, TvManagementService_SetItemTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) GetItemTags(ctx context.Context, in *GetItemTagsRequest, opts ...grpc.CallOption) (*GetItemTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemTagsResponse)
	err := c.cc.Invoke(ctx, TvManagementService_GetItemTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*GetCalendarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCalendarResponse)
	err := c.cc.Invoke(ctx, TvManagementService_GetCalendar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) ListAlternateTitles(ctx context.Context, in *ListAlternateTitlesRequest, opts ...grpc.CallOption) (*ListAlternateTitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlternateTitlesResponse)
	err := c.cc.Invoke(ctx, TvManagementService_ListAlternateTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) AddAlternateTitle(ctx context.Context, in *AddAlternateTitleRequest, opts ...grpc.CallOption) (*AddAlternateTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAlternateTitleResponse)
	err := c.cc.Invoke(ctx, TvManagementService_AddAlternateTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) RemoveAlternateTitle(ctx context.Context, in *RemoveAlternateTitleRequest, opts ...grpc.CallOption) (*RemoveAlternateTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAlternateTitleResponse)
	err := c.cc.Invoke(ctx, TvManagementService_RemoveAlternateTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvManagementServiceClient) LookupEpisode(ctx context.Context, in *LookupEpisodeRequest, opts ...grpc.CallOption) (*LookupEpisodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupEpisodeResponse)
	err := c.cc.Invoke(ctx, TvManagementService_LookupEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TvManagementServiceServer is the server API for TvManagementService service.
// All implementations must embed UnimplementedTvManagementServiceServer
// for forward compatibility.
type TvManagementServiceServer interface {
	AddTVShow(context.Context, *AddTVShowRequest) (*AddTVShowResponse, error)
	RemoveTVShow(context.Context, *RemoveTVShowRequest) (*RemoveTVShowResponse, error)
	RefreshMetadata(context.Context, *RefreshMetadataRequest) (*RefreshMetadataResponse, error)
	ListTVShows(context.Context, *ListTVShowsRequest) (*ListTVShowsResponse, error)
	ListMissing(context.Context, *ListMissingRequest) (*ListMissingResponse, error)
	GetTVShow(context.Context, *GetTVShowRequest) (*GetTVShowResponse, error)
	UpdateTVShow(context.Context, *UpdateTVShowRequest) (*UpdateTVShowResponse, error)
	UpdateEpisodeMonitored(context.Context, *UpdateEpisodeMonitoredRequest) (*UpdateEpisodeMonitoredResponse, error)
	UpdateSeasonMonitored(context.Context, *UpdateSeasonMonitoredRequest) (*UpdateSeasonMonitoredResponse, error)
	AddEpisodeFile(context.Context, *AddEpisodeFileRequest) (*AddEpisodeFileResponse, error)
	RemoveEpisodeFile(context.Context, *RemoveEpisodeFileRequest) (*RemoveEpisodeFileResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	SetItemTags(context.Context, *SetItemTagsRequest) (*SetItemTagsResponse, error)
	GetItemTags(context.Context, *GetItemTagsRequest) (*GetItemTagsResponse, error)
	GetCalendar(context.Context, *GetCalendarRequest) (*GetCalendarResponse, error)
	ListAlternateTitles(context.Context, *ListAlternateTitlesRequest) (*ListAlternateTitlesResponse, error)
	AddAlternateTitle(context.Context, *AddAlternateTitleRequest) (*AddAlternateTitleResponse, error)
	RemoveAlternateTitle(context.Context, *RemoveAlternateTitleRequest) (*RemoveAlternateTitleResponse, error)
	LookupEpisode(context.Context, *LookupEpisodeRequest) (*LookupEpisodeResponse, error)
	mustEmbedUnimplementedTvManagementServiceServer()
}

// UnimplementedTvManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTvManagementServiceServer struct{}

func (UnimplementedTvManagementServiceServer) AddTVShow(context.Context, *AddTVShowRequest) (*AddTVShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTVShow not implemented")
}
func (UnimplementedTvManagementServiceServer) RemoveTVShow(context.Context, *RemoveTVShowRequest) (*RemoveTVShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTVShow not implemented")
}
func (UnimplementedTvManagementServiceServer) RefreshMetadata(context.Context, *RefreshMetadataRequest) (*RefreshMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshMetadata not implemented")
}
func (UnimplementedTvManagementServiceServer) ListTVShows(context.Context, *ListTVShowsRequest) (*ListTVShowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTVShows not implemented")
}
func (UnimplementedTvManagementServiceServer) ListMissing(context.Context, *ListMissingRequest) (*ListMissingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMissing not implemented")
}
func (UnimplementedTvManagementServiceServer) GetTVShow(context.Context, *GetTVShowRequest) (*GetTVShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTVShow not implemented")
}
func (UnimplementedTvManagementServiceServer) UpdateTVShow(context.Context, *UpdateTVShowRequest) (*UpdateTVShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTVShow not implemented")
}
func (UnimplementedTvManagementServiceServer) UpdateEpisodeMonitored(context.Context, *UpdateEpisodeMonitoredRequest) (*UpdateEpisodeMonitoredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEpisodeMonitored not implemented")
}
func (UnimplementedTvManagementServiceServer) UpdateSeasonMonitored(context.Context, *UpdateSeasonMonitoredRequest) (*UpdateSeasonMonitoredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSeasonMonitored not implemented")
}
func (UnimplementedTvManagementServiceServer) AddEpisodeFile(context.Context, *AddEpisodeFileRequest) (*AddEpisodeFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEpisodeFile not implemented")
}
func (UnimplementedTvManagementServiceServer) RemoveEpisodeFile(context.Context, *RemoveEpisodeFileRequest) (*RemoveEpisodeFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEpisodeFile not implemented")
}
func (UnimplementedTvManagementServiceServer) CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedTvManagementServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedTvManagementServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedTvManagementServiceServer) SetItemTags(context.Context, *SetItemTagsRequest) (*SetItemTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetItemTags not implemented")
}
func (UnimplementedTvManagementServiceServer) GetItemTags(context.Context, *GetItemTagsRequest) (*GetItemTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemTags not implemented")
}
func (UnimplementedTvManagementServiceServer) GetCalendar(context.Context, *GetCalendarRequest) (*GetCalendarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCalendar not implemented")
}
func (UnimplementedTvManagementServiceServer) ListAlternateTitles(context.Context, *ListAlternateTitlesRequest) (*ListAlternateTitlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlternateTitles not implemented")
}
func (UnimplementedTvManagementServiceServer) AddAlternateTitle(context.Context, *AddAlternateTitleRequest) (*AddAlternateTitleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAlternateTitle not implemented")
}
func (UnimplementedTvManagementServiceServer) RemoveAlternateTitle(context.Context, *RemoveAlternateTitleRequest) (*RemoveAlternateTitleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAlternateTitle not implemented")
}
func (UnimplementedTvManagementServiceServer) LookupEpisode(context.Context, *LookupEpisodeRequest) (*LookupEpisodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupEpisode not implemented")
}
func (UnimplementedTvManagementServiceServer) mustEmbedUnimplementedTvManagementServiceServer() {}
func (UnimplementedTvManagementServiceServer) testEmbeddedByValue()                             {}

// UnsafeTvManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TvManagementServiceServer will
// result in compilation errors.
type UnsafeTvManagementServiceServer interface {
	mustEmbedUnimplementedTvManagementServiceServer()
}

func RegisterTvManagementServiceServer(s grpc.ServiceRegistrar, srv TvManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedTvManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TvManagementService_ServiceDesc, srv)
}

func _TvManagementService_AddTVShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTVShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).AddTVShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_AddTVShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).AddTVShow(ctx, req.(*AddTVShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_RemoveTVShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTVShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).RemoveTVShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_RemoveTVShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).RemoveTVShow(ctx, req.(*RemoveTVShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_RefreshMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).RefreshMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_RefreshMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).RefreshMetadata(ctx, req.(*RefreshMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_ListTVShows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTVShowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).ListTVShows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_ListTVShows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).ListTVShows(ctx, req.(*ListTVShowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_ListMissing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMissingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).ListMissing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_ListMissing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).ListMissing(ctx, req.(*ListMissingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_GetTVShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTVShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).GetTVShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_GetTVShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).GetTVShow(ctx, req.(*GetTVShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_UpdateTVShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTVShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).UpdateTVShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_UpdateTVShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).UpdateTVShow(ctx, req.(*UpdateTVShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_UpdateEpisodeMonitored_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEpisodeMonitoredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).UpdateEpisodeMonitored(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_UpdateEpisodeMonitored_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).UpdateEpisodeMonitored(ctx, req.(*UpdateEpisodeMonitoredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_UpdateSeasonMonitored_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSeasonMonitoredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).UpdateSeasonMonitored(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_UpdateSeasonMonitored_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).UpdateSeasonMonitored(ctx, req.(*UpdateSeasonMonitoredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_AddEpisodeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEpisodeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).AddEpisodeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_AddEpisodeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).AddEpisodeFile(ctx, req.(*AddEpisodeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_RemoveEpisodeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEpisodeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).RemoveEpisodeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_RemoveEpisodeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).RemoveEpisodeFile(ctx, req.(*RemoveEpisodeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_SetItemTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).SetItemTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_SetItemTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).SetItemTags(ctx, req.(*SetItemTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_GetItemTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).GetItemTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_GetItemTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).GetItemTags(ctx, req.(*GetItemTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_GetCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).GetCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_GetCalendar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).GetCalendar(ctx, req.(*GetCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_ListAlternateTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlternateTitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).ListAlternateTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_ListAlternateTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).ListAlternateTitles(ctx, req.(*ListAlternateTitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_AddAlternateTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAlternateTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).AddAlternateTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_AddAlternateTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).AddAlternateTitle(ctx, req.(*AddAlternateTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_RemoveAlternateTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAlternateTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).RemoveAlternateTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_RemoveAlternateTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).RemoveAlternateTitle(ctx, req.(*RemoveAlternateTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvManagementService_LookupEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvManagementServiceServer).LookupEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TvManagementService_LookupEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvManagementServiceServer).LookupEpisode(ctx, req.(*LookupEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TvManagementService_ServiceDesc is the grpc.ServiceDesc for TvManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TvManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.media.tv.v1.TvManagementService",
	HandlerType: (*TvManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTVShow",
			Handler:    _TvManagementService_AddTVShow_Handler,
		},
		{
			MethodName: "RemoveTVShow",
			Handler:    _TvManagementService_RemoveTVShow_Handler,
		},
		{
			MethodName: "RefreshMetadata",
			Handler:    _TvManagementService_RefreshMetadata_Handler,
		},
		{
			MethodName: "ListTVShows",
			Handler:    _TvManagementService_ListTVShows_Handler,
		},
		{
			MethodName: "ListMissing",
			Handler:    _TvManagementService_ListMissing_Handler,
		},
		{
			MethodName: "GetTVShow",
			Handler:    _TvManagementService_GetTVShow_Handler,
		},
		{
			MethodName: "UpdateTVShow",
			Handler:    _TvManagementService_UpdateTVShow_Handler,
		},
		{
			MethodName: "UpdateEpisodeMonitored",
			Handler:    _TvManagementService_UpdateEpisodeMonitored_Handler,
		},
		{
			MethodName: "UpdateSeasonMonitored",
			Handler:    _TvManagementService_UpdateSeasonMonitored_Handler,
		},
		{
			MethodName: "AddEpisodeFile",
			Handler:    _TvManagementService_AddEpisodeFile_Handler,
		},
		{
			MethodName: "RemoveEpisodeFile",
			Handler:    _TvManagementService_RemoveEpisodeFile_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _TvManagementService_CreateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _TvManagementService_DeleteTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _TvManagementService_ListTags_Handler,
		},
		{
			MethodName: "SetItemTags",
			Handler:    _TvManagementService_SetItemTags_Handler,
		},
		{
			MethodName: "GetItemTags",
			Handler:    _TvManagementService_GetItemTags_Handler,
		},
		{
			MethodName: "GetCalendar",
			Handler:    _TvManagementService_GetCalendar_Handler,
		},
		{
			MethodName: "ListAlternateTitles",
			Handler:    _TvManagementService_ListAlternateTitles_Handler,
		},
		{
			MethodName: "AddAlternateTitle",
			Handler:    _TvManagementService_AddAlternateTitle_Handler,
		},
		{
			MethodName: "RemoveAlternateTitle",
			Handler:    _TvManagementService_RemoveAlternateTitle_Handler,
		},
		{
			MethodName: "LookupEpisode",
			Handler:    _TvManagementService_LookupEpisode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tvmgmtv1/tvshows.proto",
}
